services:
  - type: web
    name: flitflok-backend
    runtime: docker
    repo: https://github.com/KnowYourLines/flitflok-backend.git
    region: ohio
    plan: free
    branch: main
    dockerCommand: bash -c 'python manage.py makemigrations api; python manage.py migrate; python manage.py collectstatic --no-input; gunicorn --bind 0.0.0.0:$PORT server.wsgi:application'
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: DEBUG
        value: False
      - key: LOCAL
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: flitflok-db
          property: connectionString

databases:
  - name: flitflok-db
    plan: free
    region: ohio
    postgresMajorVersion: 14
    ipAllowList: [] # only allow internal connections
