# Generated by Django 4.2.9 on 2024-02-23 12:06
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [CreateExtension("postgis")]
