# Generated by Django 4.2.10 on 2024-03-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_postgis'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_eula',
            field=models.BooleanField(default=False),
        ),
    ]
