# Generated by Django 4.2.10 on 2024-03-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_id',
            field=models.UUIDField(unique=True),
        ),
    ]
