# Generated by Django 4.2.10 on 2024-03-23 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_video_file_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="hidden_from",
            field=models.ManyToManyField(
                related_name="hidden_videos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="reported_by",
            field=models.ManyToManyField(
                related_name="reported_videos", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
