# Generated by Django 4.2.10 on 2024-04-22 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_user_blocked_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="directions_requested_by",
            field=models.ManyToManyField(
                related_name="directions_requested_videos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="number_finished_views",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
