# Generated by Django 4.2.10 on 2024-05-30 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_video_directions_requested_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="number_finished_views",
        ),
    ]
