# Generated by Django 4.2.13 on 2024-06-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_video_number_finished_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
