# Generated by Django 4.2.13 on 2024-06-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_user_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=28, null=True, unique=True),
        ),
    ]
