# Generated by Django 4.2.13 on 2024-06-10 20:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_user_display_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="video",
            name="file_id",
        ),
        migrations.AddField(
            model_name="video",
            name="playback_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
