# Generated by Django 4.2.13 on 2024-06-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_video_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="asset_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
