# Generated by Django 4.2.13 on 2024-06-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_video_asset_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="location_purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Food & Drink", "Food & Drink"),
                    ("Recreation & Entertainment", "Recreation & Entertainment"),
                    ("Landmarks & Attractions", "Landmarks & Attractions"),
                    ("Shopping", "Shopping"),
                    ("Facilities & Services", "Facilities & Services"),
                ],
                max_length=255,
            ),
        ),
    ]
