# Generated by Django 4.2.13 on 2024-07-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_remove_video_address_remove_video_place_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="cloudflare_video_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
