# Generated by Django 4.2.13 on 2024-07-05 19:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_remove_video_address_remove_video_place_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="asset_id",
            new_name="cloudflare_uid",
        ),
        migrations.RemoveField(
            model_name="video",
            name="playback_id",
        ),
        migrations.AddField(
            model_name="video",
            name="hls",
            field=models.URLField(default="https://google.com"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.URLField(default="https://google.com"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default="SRID=4326;POINT(0 1)", srid=4326
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
