# Generated by Django 4.2.13 on 2024-07-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_rename_asset_id_video_cloudflare_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="preview",
            field=models.URLField(default="https://google.com"),
            preserve_default=False,
        ),
    ]
