# Generated by Django 4.2.13 on 2024-07-05 23:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_video_preview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="cloudflare_uid",
        ),
    ]
