# Generated by Django 4.2.13 on 2024-07-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_video_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="cloudflare_uid",
            field=models.CharField(default="hello", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
