# Generated by Django 4.2.13 on 2024-07-05 23:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_remove_video_cloudflare_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="cloudflare_uid",
            field=models.CharField(default=uuid.uuid4, max_length=255, null=True),
        ),
    ]
