# Generated by Django 4.2.13 on 2024-07-05 23:53
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Video = apps.get_model("api", "Video")
    for row in Video.objects.all():
        row.cloudflare_uid = uuid.uuid4()
        row.save(update_fields=["cloudflare_uid"])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_video_cloudflare_uid"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
