# Generated by Django 4.2.13 on 2024-07-05 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_auto_20240705_2353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="cloudflare_uid",
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
