# Generated by Django 4.2.13 on 2024-07-31 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_auto_20240705_2353"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="location_purpose",
        ),
    ]
