# Generated by Django 4.2.13 on 2024-08-28 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_buddyrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="starring",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos_starring",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
